// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpksnwrvclhmflpcbuci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwa3Nud3J2Y2xobWZscGNidWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxOTQ5NjQsImV4cCI6MjA5Nzc3MDk2NH0.2o_SgP3nPABtXliCZoiDg-0VnCRa7XKjyaBlJ14qqsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});